### PR TITLE
Added Readme and Fixed category filter

### PR DESCRIPTION
**Pull request by vrinda-mahajan**

### CODE REVIEW

**Review by ApurvaSawant11 — APPROVED** [review]
Looks good to me! You can merge the PR

**Review by Developers-codz — APPROVED** [review]
Everything Looks good to merge
Good that you added readme

**Review by VLeads — APPROVED** [review]
It's looking good. You can merge.

**Comment by vrinda-mahajan** [comment]
Thanks @ApurvaSawant11 , @Developers-codz , @VLeads  for reviewing the PR.

**Pull request merged**
